// src/services/mockData.js

export const mockProducts = [
  {
    sku: 'SOFA-001',
    name: 'Modern Velvet Sofa',
    price: 899,
    discount_price: 799,
    image_path: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
    category: 'sofa',
    description: 'A beautiful and comfortable modern velvet sofa perfect for any living room. Upholstered in premium velvet fabric with sturdy metallic legs.',
    wood_type: 'pine',
    finish: 'natural',
    dimensions: '200x90x85 cm',
    weight: 45,
    stock: 12,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['modern', 'velvet', 'living room']
  },
  {
    sku: 'CHAIR-001',
    name: 'Ergonomic Wooden Chair',
    price: 199,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=500',
    category: 'chair',
    description: 'Minimalist ergonomic chair suitable for dining or office use. Features a gently sloped backrest for extended comfort.',
    wood_type: 'oak',
    finish: 'light',
    dimensions: '45x50x85 cm',
    weight: 8,
    stock: 30,
    status: 'active',
    featured: true,
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['minimalist', 'ergonomic', 'dining']
  },
  {
    sku: 'TABLE-001',
    name: 'Solid Walnut Dining Table',
    price: 1299,
    discount_price: 1100,
    image_path: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=500',
    category: 'table',
    description: 'Large solid walnut dining table that comfortably seats 8 people. Finished with natural oils to highlight the rich wood grain.',
    wood_type: 'walnut',
    finish: 'dark',
    dimensions: '220x100x75 cm',
    weight: 65,
    stock: 5,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['dining', 'walnut', 'large']
  },
  {
    sku: 'BED-001',
    name: 'Platform Queen Bed',
    price: 850,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500',
    category: 'matress',
    description: 'Sturdy wooden platform bed with a sleek modern design. Perfect for minimalist bedroom setups.',
    wood_type: 'maple',
    finish: 'medium',
    dimensions: '160x200x35 cm',
    weight: 55,
    stock: 8,
    status: 'active',
    featured: false,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['bedroom', 'modern', 'queen']
  },
  {
    sku: 'LAMP-001',
    name: 'Industrial Floor Lamp',
    price: 149,
    discount_price: 129,
    image_path: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500',
    category: 'lamp',
    description: 'Tall industrial style floor lamp with adjustable head. Matte black finish casts a focused ambient light.',
    wood_type: 'none',
    finish: 'dark',
    dimensions: '40x40x160 cm',
    weight: 12,
    stock: 20,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['industrial', 'lighting', 'metal']
  },
  {
    sku: 'DESK-001',
    name: 'Standing Office Desk',
    price: 499,
    discount_price: 450,
    image_path: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500',
    category: 'desk',
    description: 'Premium adjustable standing desk with natural bamboo top and dual electric motors.',
    wood_type: 'bamboo',
    finish: 'natural',
    dimensions: '140x70x75-120 cm',
    weight: 35,
    stock: 15,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['office', 'standing', 'adjustable']
  },
  {
    sku: 'SOFA-002',
    name: 'Leather Chesterfield Sofa',
    price: 1599,
    discount_price: 1350,
    image_path: 'https://images.unsplash.com/photo-1540574163026-643ea20d25b5?w=500',
    category: 'sofa',
    description: 'Classic genuine leather Chesterfield sofa with deep button tufting and rolled arms.',
    wood_type: 'oak',
    finish: 'dark',
    dimensions: '210x95x80 cm',
    weight: 60,
    stock: 4,
    status: 'active',
    featured: true,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['leather', 'classic', 'living room', 'sofa']
  },
  {
    sku: 'CHAIR-002',
    name: 'Velvet Accent Chair',
    price: 350,
    discount_price: 299,
    image_path: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500',
    category: 'chair',
    description: 'Plush velvet accent chair with gold-finished metal legs for a touch of glamour.',
    wood_type: 'none',
    finish: 'gold',
    dimensions: '60x65x80 cm',
    weight: 12,
    stock: 18,
    status: 'active',
    featured: false,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['velvet', 'chair', 'accent', 'modern']
  },
  {
    sku: 'TABLE-002',
    name: 'Round Glass Coffee Table',
    price: 299,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1532372576444-dda9541a4aa4?w=500',
    category: 'table',
    description: 'Minimalist round coffee table with a tempered glass top and solid oak criss-cross base.',
    wood_type: 'oak',
    finish: 'natural',
    dimensions: '90x90x45 cm',
    weight: 22,
    stock: 10,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['coffee table', 'glass', 'living room']
  },
  {
    sku: 'BED-002',
    name: 'Memory Foam Mattress',
    price: 699,
    discount_price: 550,
    image_path: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=500',
    category: 'matress',
    description: 'Premium 12-inch memory foam mattress with cooling gel technology for perfect sleep.',
    wood_type: 'none',
    finish: 'none',
    dimensions: '150x200x30 cm',
    weight: 30,
    stock: 25,
    status: 'active',
    featured: false,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['bedroom', 'mattress', 'memory foam']
  },
  {
    sku: 'LAMP-002',
    name: 'Ceramic Table Lamp',
    price: 85,
    discount_price: 65,
    image_path: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
    category: 'lamp',
    description: 'Textured ceramic table lamp with a natural linen drum shade. Warm ambient lighting.',
    wood_type: 'none',
    finish: 'white',
    dimensions: '30x30x55 cm',
    weight: 4,
    stock: 40,
    status: 'active',
    featured: false,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['lighting', 'ceramic', 'bedroom', 'lamp']
  },
  {
    sku: 'KITCHEN-001',
    name: 'Rustic Kitchen Island',
    price: 799,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1556909114-f6e7a7c6f1e2?w=500',
    category: 'kitchen',
    description: 'Mobile kitchen island cart with a solid butcher block top and ample storage underneath.',
    wood_type: 'maple',
    finish: 'natural',
    dimensions: '120x60x90 cm',
    weight: 45,
    stock: 6,
    status: 'active',
    featured: true,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['kitchen', 'island', 'storage', 'wood']
  },
  {
    sku: 'DECOR-001',
    name: 'Minimalist Ceramic Vase',
    price: 45,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=500',
    category: 'decor',
    description: 'Elegant white ceramic vase perfect for dried pampas grass or fresh flowers.',
    wood_type: 'none',
    finish: 'matte white',
    dimensions: '15x15x35 cm',
    weight: 2,
    stock: 50,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['decor', 'vase', 'ceramic', 'minimalist']
  },
  {
    sku: 'SOFA-003',
    name: 'L-Shaped Sectional Sofa',
    price: 1899,
    discount_price: 1599,
    image_path: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=500',
    category: 'sofa',
    description: 'Spacious L-shaped sectional sofa in durable grey fabric. Perfect for large families.',
    wood_type: 'pine',
    finish: 'light',
    dimensions: '280x200x85 cm',
    weight: 85,
    stock: 3,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['sofa', 'sectional', 'living room', 'fabric']
  },
  {
    sku: 'DESK-002',
    name: 'Compact Writing Desk',
    price: 199,
    discount_price: 150,
    image_path: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500',
    category: 'desk',
    description: 'Small space writing desk with two sliding drawers and mid-century modern legs.',
    wood_type: 'walnut',
    finish: 'medium',
    dimensions: '100x50x75 cm',
    weight: 15,
    stock: 20,
    status: 'active',
    featured: false,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['desk', 'office', 'compact', 'wood']
  },
  {
    sku: 'OUTDOOR-001',
    name: 'Patio Lounge Set',
    price: 1100,
    discount_price: 999,
    image_path: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500',
    category: 'garden',
    description: 'Weather-resistant outdoor rattan lounge set including two chairs and a coffee table.',
    wood_type: 'rattan',
    finish: 'natural',
    dimensions: 'Various',
    weight: 40,
    stock: 5,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['outdoor', 'patio', 'rattan', 'garden']
  },
  {
    sku: 'STOOL-001',
    name: 'Velvet Storage Ottoman',
    price: 129,
    discount_price: 99,
    image_path: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500',
    category: 'stool',
    description: 'Multifunctional velvet ottoman with hidden storage compartment inside.',
    wood_type: 'none',
    finish: 'gold',
    dimensions: '45x45x40 cm',
    weight: 5,
    stock: 12,
    status: 'active',
    featured: false,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['stool', 'velvet', 'storage']
  },
  {
    sku: 'STOOL-002',
    name: 'Wooden Bar Stool',
    price: 89,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=500',
    category: 'stool',
    description: 'Classic wooden counter-height bar stool with a saddle seat.',
    wood_type: 'oak',
    finish: 'medium',
    dimensions: '40x40x75 cm',
    weight: 6,
    stock: 24,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['bar', 'kitchen', 'stool', 'wooden']
  },
  {
    sku: 'TVTABLE-001',
    name: 'Modern TV Stand',
    price: 399,
    discount_price: 349,
    image_path: 'https://images.unsplash.com/photo-1532372576444-dda9541a4aa4?w=500',
    category: 'tv table',
    description: 'Low-profile modern TV stand for screens up to 65 inches, with cable management.',
    wood_type: 'walnut',
    finish: 'dark',
    dimensions: '160x40x45 cm',
    weight: 28,
    stock: 8,
    status: 'active',
    featured: false,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['tv', 'living room', 'media']
  },
  {
    sku: 'TVTABLE-002',
    name: 'Floating TV Unit',
    price: 249,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500',
    category: 'tv table',
    description: 'Wall-mounted floating TV console to save floor space.',
    wood_type: 'maple',
    finish: 'light',
    dimensions: '120x30x25 cm',
    weight: 15,
    stock: 10,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['floating', 'minimalist', 'tv']
  },
  {
    sku: 'WARDROBE-001',
    name: 'Double Door Wardrobe',
    price: 899,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1556909114-f6e7a7c6f1e2?w=500',
    category: 'wardrove',
    description: 'Spacious double door wardrobe with internal drawers and hanging rail.',
    wood_type: 'oak',
    finish: 'natural',
    dimensions: '100x60x200 cm',
    weight: 85,
    stock: 5,
    status: 'active',
    featured: true,
    created_at: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['bedroom', 'storage', 'wardrobe']
  },
  {
    sku: 'WARDROBE-002',
    name: 'Sliding Mirror Wardrobe',
    price: 1199,
    discount_price: 999,
    image_path: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=500',
    category: 'wardrove',
    description: 'Sleek sliding door wardrobe featuring full-length mirrored panels.',
    wood_type: 'pine',
    finish: 'white',
    dimensions: '150x60x210 cm',
    weight: 110,
    stock: 3,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['mirror', 'sliding', 'wardrobe']
  },
  {
    sku: 'VANITY-001',
    name: 'Bathroom Vanity Cabinet',
    price: 599,
    discount_price: 499,
    image_path: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500',
    category: 'vanitory',
    description: 'Single sink bathroom vanity with marble top and under-sink storage.',
    wood_type: 'oak',
    finish: 'white',
    dimensions: '80x50x85 cm',
    weight: 45,
    stock: 6,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['bathroom', 'vanity', 'cabinet']
  },
  {
    sku: 'MIRROR-001',
    name: 'Round Wall Mirror',
    price: 129,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=500',
    category: 'mirror',
    description: 'Large round wall mirror with a thin brass metal rim.',
    wood_type: 'none',
    finish: 'brass',
    dimensions: '80x80x2 cm',
    weight: 8,
    stock: 15,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['decor', 'mirror', 'wall']
  },
  {
    sku: 'MIRROR-002',
    name: 'Full Length Floor Mirror',
    price: 199,
    discount_price: 179,
    image_path: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500',
    category: 'mirror',
    description: 'Standing full-length floor mirror with an arched wooden frame.',
    wood_type: 'maple',
    finish: 'natural',
    dimensions: '60x4x160 cm',
    weight: 14,
    stock: 9,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['bedroom', 'mirror', 'floor']
  },
  {
    sku: 'GARDEN-002',
    name: 'Outdoor Dining Set',
    price: 899,
    discount_price: 750,
    image_path: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500',
    category: 'garden',
    description: 'Teak wood outdoor dining table with four matching folding chairs.',
    wood_type: 'teak',
    finish: 'natural',
    dimensions: '150x90x75 cm',
    weight: 55,
    stock: 5,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['outdoor', 'dining', 'teak']
  },
  {
    sku: 'GARDEN-003',
    name: 'Rattan Hammock Chair',
    price: 249,
    discount_price: 199,
    image_path: 'https://images.unsplash.com/photo-1540574163026-643ea20d25b5?w=500',
    category: 'garden',
    description: 'Suspended egg-shaped rattan hammock chair with comfortable outdoor cushions.',
    wood_type: 'rattan',
    finish: 'natural',
    dimensions: '90x90x110 cm',
    weight: 18,
    stock: 12,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['outdoor', 'lounge', 'hammock']
  },
  {
    sku: 'KITCHEN-002',
    name: 'Kitchen Pantry Cabinet',
    price: 499,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1556909114-f6e7a7c6f1e2?w=500',
    category: 'kitchen',
    description: 'Tall freestanding kitchen pantry with adjustable shelves.',
    wood_type: 'pine',
    finish: 'white',
    dimensions: '80x40x180 cm',
    weight: 60,
    stock: 7,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['kitchen', 'storage', 'cabinet']
  },
  {
    sku: 'DESK-003',
    name: 'Executive Office Desk',
    price: 899,
    discount_price: 800,
    image_path: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=500',
    category: 'desk',
    description: 'Massive solid walnut executive desk with built-in leather writing pad.',
    wood_type: 'walnut',
    finish: 'dark',
    dimensions: '180x80x75 cm',
    weight: 75,
    stock: 2,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['office', 'desk', 'executive']
  },
  {
    sku: 'BED-003',
    name: 'Kids Bunk Bed',
    price: 699,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500',
    category: 'matress',
    description: 'Safe and sturdy twin-over-twin bunk bed with an integrated ladder.',
    wood_type: 'pine',
    finish: 'white',
    dimensions: '200x100x160 cm',
    weight: 80,
    stock: 8,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['bedroom', 'kids', 'bunk bed']
  },
  {
    sku: 'MATTRESS-001',
    name: 'Twin Spring Mattress',
    price: 299,
    discount_price: 249,
    image_path: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=500',
    category: 'matress',
    description: 'Classic innerspring twin mattress with breathable cotton cover.',
    wood_type: 'none',
    finish: 'white',
    dimensions: '100x200x20 cm',
    weight: 20,
    stock: 30,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['bedroom', 'mattress', 'twin']
  },
  {
    sku: 'TABLE-003',
    name: 'Glass Dining Table',
    price: 599,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1532372576444-dda9541a4aa4?w=500',
    category: 'table',
    description: 'Modern dining table featuring a thick tempered glass top and geometric steel legs.',
    wood_type: 'none',
    finish: 'black',
    dimensions: '160x90x75 cm',
    weight: 45,
    stock: 14,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['dining', 'glass', 'modern']
  },
  {
    sku: 'TABLE-004',
    name: 'Marble Side Table',
    price: 199,
    discount_price: 179,
    image_path: 'https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=500',
    category: 'table',
    description: 'Chic C-shaped side table with a genuine white marble top.',
    wood_type: 'none',
    finish: 'brass',
    dimensions: '40x40x60 cm',
    weight: 12,
    stock: 22,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['living room', 'side table', 'marble']
  },
  {
    sku: 'CHAIR-003',
    name: 'Recliner Armchair',
    price: 499,
    discount_price: 399,
    image_path: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=500',
    category: 'chair',
    description: 'Ultra-comfortable manual reclining armchair upholstered in soft microfiber.',
    wood_type: 'pine',
    finish: 'grey',
    dimensions: '85x95x105 cm',
    weight: 35,
    stock: 11,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['living room', 'recliner', 'comfort']
  },
  {
    sku: 'CHAIR-004',
    name: 'Bouclé Accent Chair',
    price: 329,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=500',
    category: 'chair',
    description: 'Trendy curved accent chair upholstered in cozy white bouclé fabric.',
    wood_type: 'none',
    finish: 'white',
    dimensions: '75x70x75 cm',
    weight: 16,
    stock: 15,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['accent', 'boucle', 'modern']
  },
  {
    sku: 'SOFA-004',
    name: '3-Seater Fabric Sofa',
    price: 799,
    discount_price: 699,
    image_path: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
    category: 'sofa',
    description: 'Everyday comfortable 3-seater sofa wrapped in stain-resistant linen.',
    wood_type: 'oak',
    finish: 'light',
    dimensions: '210x90x85 cm',
    weight: 55,
    stock: 7,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['sofa', 'fabric', 'living room']
  },
  {
    sku: 'SOFA-005',
    name: 'Convertible Sofa Bed',
    price: 599,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1540574163026-643ea20d25b5?w=500',
    category: 'sofa',
    description: 'Futon-style convertible sofa bed, perfect for hosting overnight guests.',
    wood_type: 'maple',
    finish: 'medium',
    dimensions: '190x110x40 cm',
    weight: 45,
    stock: 19,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['sofa', 'bed', 'convertible']
  },
  {
    sku: 'LAMP-003',
    name: 'Brass Wall Sconce',
    price: 75,
    discount_price: 59,
    image_path: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500',
    category: 'lamp',
    description: 'Elegant brass wall sconce with a frosted glass globe.',
    wood_type: 'none',
    finish: 'brass',
    dimensions: '20x15x25 cm',
    weight: 2,
    stock: 35,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['lighting', 'wall', 'brass']
  },
  {
    sku: 'LAMP-004',
    name: 'Rattan Pendant Light',
    price: 119,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500',
    category: 'lamp',
    description: 'Handwoven rattan pendant light bringing a bohemian touch to any room.',
    wood_type: 'rattan',
    finish: 'natural',
    dimensions: '40x40x40 cm',
    weight: 3,
    stock: 18,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['lighting', 'pendant', 'rattan']
  },
  {
    sku: 'DECOR-002',
    name: 'Macrame Wall Hanging',
    price: 65,
    discount_price: 49,
    image_path: 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?w=500',
    category: 'decor',
    description: 'Large handmade macrame tapestry on a natural driftwood branch.',
    wood_type: 'driftwood',
    finish: 'natural',
    dimensions: '80x2x120 cm',
    weight: 2,
    stock: 14,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['decor', 'wall', 'boho']
  },
  {
    sku: 'DECOR-003',
    name: 'Faux Potted Monstera',
    price: 89,
    discount_price: null,
    image_path: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=500',
    category: 'decor',
    description: 'Lifelike faux Monstera Deliciosa plant in a minimalist white ceramic pot.',
    wood_type: 'none',
    finish: 'white',
    dimensions: '40x40x120 cm',
    weight: 5,
    stock: 25,
    status: 'active',
    featured: true,
    created_at: new Date().toISOString(),
    tags: ['decor', 'plant', 'faux']
  },
  {
    sku: 'DECOR-004',
    name: 'Geometric Pattern Rug',
    price: 249,
    discount_price: 199,
    image_path: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500',
    category: 'decor',
    description: 'Soft wool blend area rug featuring a modern tribal geometric pattern.',
    wood_type: 'none',
    finish: 'none',
    dimensions: '160x230x2 cm',
    weight: 12,
    stock: 8,
    status: 'active',
    featured: false,
    created_at: new Date().toISOString(),
    tags: ['decor', 'rug', 'textile']
  }
];

export const getMockProducts = (params = {}) => {
  let filtered = [...mockProducts];
  
  if (params.category && params.category !== 'all') {
    filtered = filtered.filter(p => p.category === params.category);
  }
  
  if (params.name) {
    const q = params.name.toLowerCase();
    filtered = filtered.filter(p => p.name.toLowerCase().includes(q));
  }
  
  if (params.featured) {
    filtered = filtered.filter(p => p.featured);
  }
  
  if (params.sort) {
    if (params.sort === 'newest') {
      filtered.sort((a,b) => new Date(b.created_at) - new Date(a.created_at));
    } else if (params.sort === 'price_asc') {
      filtered.sort((a,b) => (a.discount_price || a.price) - (b.discount_price || b.price));
    }
  }
  
  if (params.limit) {
    filtered = filtered.slice(0, params.limit);
  }

  return {
    success: true,
    data: filtered,
    count: filtered.length,
    page: 1,
    totalPages: 1
  };
};

export const getMockProductBySku = (sku) => {
  const product = mockProducts.find(p => p.sku === sku);
  if (product) {
    return { success: true, data: product };
  }
  return { success: false, error: 'Product not found' };
};
